name: 'OpenShift Client Installer'
description: "Install the OpenShift Client (oc) into an action runner"
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  oc_version:
    description: |
      "oc version to install. It can be a version (eg. 4.6) or a URL pointing to an oc download.
      If left blank, the latest oc is installed."
    default: 'latest'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
