name: Link checker
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  markdown-link-check:
     steps:
    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '4.6'
  # Now, oc is available for the rest of these steps.
    name: Check links in markdown
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: true
