"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LINUX = 'linux';
exports.MACOSX = 'macosx';
exports.WIN = 'windows';
exports.LATEST = 'latest';
exports.OC_TAR_GZ = 'oc.tar.gz';
exports.OC_ZIP = 'oc.zip';
exports.OPENSHIFT_SERVICE_NAME = 'openshiftService';
exports.BASIC_AUTHENTICATION = 'UsernamePassword';
exports.TOKEN_AUTHENTICATION = 'Token';
exports.NO_AUTHENTICATION = 'None';
