name: oc-installer Platform Test
on: [push, workflow_dispatch]

jobs:
  install:
    name: oc Install
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        oc_version: [latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout oc installer action github repository
      - name: Checkout oc-installer action
        uses: actions/checkout@v2

      - name: Install
        uses: ./
        with:
          oc_version: ${{ matrix.oc_version }}

      # oc 3 doesn't have --client flag
      - name: Test (v3)
        if: "startsWith(matrix.oc_version, '3')"
        run: |
          oc version

      - name: Test (v4)
        if: "startsWith(matrix.oc_version, '4') || matrix.oc_version == 'latest'"
        run: |
          oc version --client
