name: oc-installer Versions Test
on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  install:
    name: oc Install
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        oc_version: [ 3.11.173, 4.6, 'https://mirror.openshift.com/pub/openshift-v3/clients/3.11.318/linux/oc.tar.gz' ]
    runs-on: ${{ matrix.os }}

    steps:

      # Checkout oc installer action github repository
      - name: Checkout oc-installer action
        uses: actions/checkout@v2

      - name: Install
        uses: ./
        with:
          oc_version: ${{ matrix.oc_version }}

      # oc 3 doesn't have --client flag
      - name: Test (v3)
        if: "startsWith(matrix.oc_version, '3') || contains(matrix.oc_version, 'openshift-v3')"
        run: |
          oc version

      - name: Test (v4)
        if: "startsWith(matrix.oc_version, '4')"
        run: |
          oc version --client
